# Spring actuator end-points config
management.endpoints.access.default=none
management.endpoint.health.access=read_only
management.endpoints.web.base-path=/item-handler/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.health.mongodb.enabled=false

# OpenTelemetry configuration
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics

spring.data.mongodb.repositories.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

uk.gov.companieshouse.item-handler.error-consumer = ${IS_ERROR_QUEUE_CONSUMER}

spring.kafka.bootstrap-servers = ${KAFKA_BROKER_ADDR}

certificate.order.confirmation.recipient = ${CERTIFICATE_ORDER_CONFIRMATION_RECIPIENT}
certified-copy.order.confirmation.recipient = ${CERTIFIED_COPY_ORDER_CONFIRMATION_RECIPIENT}
missing-image-delivery.order.confirmation.recipient = ${MISSING_IMAGE_DELIVERY_ORDER_CONFIRMATION_RECIPIENT}
dispatch-days = ${DISPATCH_DAYS}

lp.certificate.orders.enabled = ${DYNAMIC_LP_CERTIFICATE_ORDERS_ENABLED}
llp.certificate.orders.enabled = ${DYNAMIC_LLP_CERTIFICATE_ORDERS_ENABLED}

# Kafka topics
application-namespace=item-handler
kafka.topics.email-send=email-send
kafka.topics.order-received=order-received
kafka.topics.order-received_group=${application-namespace}-${kafka.topics.order-received}
kafka.topics.order-received-retry=order-received-retry
kafka.topics.order-received-retry-group=${application-namespace}-${kafka.topics.order-received-retry}
kafka.topics.order-received-error=order-received-error
kafka.topics.order-received-error-group=${application-namespace}-${kafka.topics.order-received-error}
kafka.topics.chd-item-ordered=chd-item-ordered
kafka.topics.item-group-ordered=item-group-ordered

# Order process response handler
response.handler.maximumRetryAttempts = 5
response.handler.retryTopic = ${kafka.topics.order-received-retry}
response.handler.errorTopic = ${kafka.topics.order-received-error}

# Global email properties
email.senderEmail = noreply@companieshouse.gov.uk
email.ordersAdminHost = ${CHS_URL}

# Certificate email properties
email.certificate.recipient = ${CERTIFICATE_ORDER_CONFIRMATION_RECIPIENT}
email.certificate.standardSubjectLine = CHS certificate order
email.certificate.expressSubjectLine = CHS Certificate Same day order

# Certified copy email properties
email.certifiedCopy.recipient = ${CERTIFIED_COPY_ORDER_CONFIRMATION_RECIPIENT}
email.certifiedCopy.standardSubjectLine = CHS certified copy order
email.certifiedCopy.expressSubjectLine = CHS Certified Document Same day order

# CHS Kafka API configuration
chs.kafka.api.url=${CHS_KAFKA_API_URL:}